"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const StockHeader = () => {
    return ((0, jsx_runtime_1.jsxs)("div", { className: 'mb-3 flex justify-between', children: [(0, jsx_runtime_1.jsxs)("div", { className: 'flex space-x-2', children: [(0, jsx_runtime_1.jsx)("img", { className: 'w-12 rounded-xl', src: '/images/samsung_icon.png' }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("div", { className: 'flex space-x-1', children: [(0, jsx_runtime_1.jsx)("p", { className: 'font-semibold', children: "\uC0BC\uC131\uC804\uC790" }), (0, jsx_runtime_1.jsx)("p", { className: 'text-neutral-400', children: "005930" })] }), (0, jsx_runtime_1.jsxs)("div", { className: 'flex items-baseline space-x-1', children: [(0, jsx_runtime_1.jsx)("p", { className: 'text-lg font-semibold', children: "57,000\uC6D0" }), (0, jsx_runtime_1.jsx)("p", { className: 'text-sm', children: "\uC5B4\uC81C\uBCF4\uB2E4 " }), (0, jsx_runtime_1.jsx)("p", { className: 'text-sm text-blue-500', children: "-500\uC6D0 (0.8%)" })] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: 'flex items-center space-x-3', children: [(0, jsx_runtime_1.jsx)(KeyMetric, { title: '\uC2DC\uAC00\uCD1D\uC561', value: '379.1\uC870\uC6D0' }), (0, jsx_runtime_1.jsx)(KeyMetric, { title: '1\uC77C \uCD5C\uC800', value: '379.1\uC870\uC6D0' }), (0, jsx_runtime_1.jsx)(KeyMetric, { title: '1\uC77C \uCD5C\uACE0', value: '379.1\uC870\uC6D0' }), (0, jsx_runtime_1.jsx)(KeyMetric, { title: '1\uB144 \uCD5C\uC800', value: '379.1\uC870\uC6D0' }), (0, jsx_runtime_1.jsx)(KeyMetric, { title: '1\uB144 \uCD5C\uACE0', value: '379.1\uC870\uC6D0' })] })] }));
};
const KeyMetric = ({ title, value }) => {
    return ((0, jsx_runtime_1.jsxs)("div", { className: 'flex space-x-1.5', children: [(0, jsx_runtime_1.jsx)("div", { className: 'w-0.25 my-1.5 bg-neutral-500' }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: 'text-neu-400 text-sm font-medium', children: title }), (0, jsx_runtime_1.jsx)("p", { className: 'text-sm font-medium', children: value })] })] }));
};
exports.default = StockHeader;
